# -*- coding: utf-8 -*-
"""project spam classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbywyTTFfqxw1uK8be8RQ_NCc9vC2GQ2
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
email_data = pd.read_csv('/content/archive (6).zip')
email_data.head()

email_data.shape

email_data.columns

email_data.info()

email_data.describe()

"""**Ham vs Spam**"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(6,4))
sns.countplot(x='label', data=email_data, palette='Set2')
plt.title("Distribution of Ham vs. Spam")
plt.xlabel("Label")
plt.ylabel("Count")
plt.show()

"""**Word Cloud for Ham and Spam**"""

from wordcloud import WordCloud

ham_words = ' '.join(list(email_data[email_data['label'] == 'ham']['email']))
ham_wc = WordCloud(width=500, height=300, random_state=42, max_font_size=100).generate(ham_words)

spam_words = ' '.join(list(email_data[email_data['label'] == 'spam']['email']))
spam_wc = WordCloud(width=500, height=300, random_state=42, max_font_size=100, colormap='Reds').generate(spam_words)

plt.figure(figsize=(10, 6))
plt.subplot(1, 2, 1)
plt.imshow(ham_wc, interpolation='bilinear')
plt.axis('off')
plt.title('Ham Emails')

plt.subplot(1, 2, 2)
plt.imshow(spam_wc, interpolation='bilinear')
plt.axis('off')
plt.title('Spam Emails')

plt.show()

"""**Split the Data**"""

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

"""**Train a Classifier (e.g., Naive Bayes):**"""

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_vec, y_train)

"""**Make Predictions and Evaluate:**"""

from sklearn.metrics import classification_report, accuracy_score

y_pred = model.predict(X_test_vec)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))